// components/Candle.vue
<template>
  <a
    href='https://zh.wikipedia.org/wiki/%E5%85%AD%E5%9B%9B%E4%BA%8B%E4%BB%B6'
    target='_blank'
    rel='noreferrer'
    class='candle'
  >
    🕯️
  </a>
</template>

<style>
  .candle {
    text-decoration: none;
    position: fixed;
    bottom: 1rem;
    left: 1rem;
    z-index: 99999;
    font-size: 2rem;
  }
</style>

// components/Candle.svelte
<a
  href='https://zh.wikipedia.org/wiki/%E5%85%AD%E5%9B%9B%E4%BA%8B%E4%BB%B6'
  target='_blank'
  rel='noreferrer'
  class='candle'
>
  🕯️
</a>

<style>
  .candle {
    text-decoration: none;
    position: fixed;
    bottom: 1rem;
    left: 1rem;
    z-index: 99999;
    font-size: 2rem;
  }
</style>
